services:
  expense-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: expense-api
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://expense_user:expense_pass@postgres:5432/expense_db
      - JWT_SECRET=${JWT_SECRET:?JWT_SECRET is required}
      - UPLOAD_DIR=/app/uploads
      - RECEIPT_PARSER_URL=http://receipt-parser-app:3000
      # OAuth credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID:-}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET:-}
      - FACEBOOK_REDIRECT_URI=${FACEBOOK_REDIRECT_URI:-}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - expense-network
      - caddy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=expense_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      - POSTGRES_DB=expense_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - expense-network
      - caddy-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data:
  uploads_data:

networks:
  expense-network:
    driver: bridge
  caddy-network:
    external: true
